README.md
Adding some basic information to the readme
=> Add some more information to the readme

.editorconfig, .github/workflows/dotnet-format.yml, global.json, src/OpenFeature/Constant/Error.cs, src/OpenFeature/Constant/FlagValueType.cs, src/OpenFeature/Constant/NoOpProvider.cs, src/OpenFeature/Constant/Reason.cs, src/OpenFeature/Extension/ResolutionDetailsExtensions.cs, src/OpenFeature/Hook.cs, src/OpenFeature/IFeatureClient.cs, src/OpenFeature/IFeatureProvider.cs, src/OpenFeature/Model/ClientMetadata.cs, src/OpenFeature/Model/EvaluationContext.cs, src/OpenFeature/Model/FlagEvaluationOptions.cs, src/OpenFeature/Model/FlagEvalusationDetails.cs, src/OpenFeature/Model/HookContext.cs, src/OpenFeature/Model/Metadata.cs, src/OpenFeature/Model/ResolutionDetails.cs, src/OpenFeature/NoOpProvider.cs, src/OpenFeature/OpenFeature.cs, src/OpenFeature/OpenFeatureClient.cs, test/OpenFeature.Tests/NoOpFeatureProviderTest.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/OpenFeatureEvaluationContextTests.cs, test/OpenFeature.Tests/OpenFeatureHookTests.cs, test/OpenFeature.Tests/OpenFeatureTests.cs, test/OpenFeature.Tests/TestImplementations.cs
- Add editorconfig for style rules
- Apply style rules
=> Add dotnet format workflows

README.md, build/Common.prod.props, build/Common.tests.props, build/xunit.runner.json, src/OpenFeature/Constant/ErrorType.cs, src/OpenFeature/Constant/FlagValueType.cs, src/OpenFeature/Constant/NoOpProvider.cs, src/OpenFeature/Constant/Reason.cs, src/OpenFeature/Error/FeatureProviderException.cs, src/OpenFeature/Extension/EnumExtensions.cs, src/OpenFeature/Extension/ResolutionDetailsExtensions.cs, src/OpenFeature/Hook.cs, src/OpenFeature/IFeatureClient.cs, src/OpenFeature/IFeatureProvider.cs, src/OpenFeature/Model/ClientMetadata.cs, src/OpenFeature/Model/EvaluationContext.cs, src/OpenFeature/Model/FlagEvaluationOptions.cs, src/OpenFeature/Model/FlagEvalusationDetails.cs, src/OpenFeature/Model/HookContext.cs, src/OpenFeature/Model/Metadata.cs, src/OpenFeature/Model/ResolutionDetails.cs, src/OpenFeature/NoOpProvider.cs, src/OpenFeature/OpenFeature.cs, src/OpenFeature/OpenFeature.csproj, src/OpenFeature/OpenFeatureClient.cs, test/OpenFeature.Tests/FeatureProviderExceptionTests.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/OpenFeatureTests.cs
Issue: https://github.com/open-feature/dotnet-sdk/issues/20
- Document public code using xmldoc, and generate doc file
- Avoid parallel test running to fix race condition when setting multiple provides on the Singleton instance which causes problems in the OpenFeature singleton tests
=> Add xmldoc comments to code

README.md, src/OpenFeature/Constant/ErrorType.cs, src/OpenFeature/Constant/FlagValueType.cs, src/OpenFeature/Constant/NoOpProvider.cs, src/OpenFeature/Constant/Reason.cs, src/OpenFeature/Error/FeatureProviderException.cs, src/OpenFeature/Extension/EnumExtensions.cs, src/OpenFeature/Extension/ResolutionDetailsExtensions.cs, src/OpenFeature/Hook.cs, src/OpenFeature/IFeatureClient.cs, src/OpenFeature/IFeatureProvider.cs, src/OpenFeature/Model/ClientMetadata.cs, src/OpenFeature/Model/EvaluationContext.cs, src/OpenFeature/Model/FlagEvaluationOptions.cs, src/OpenFeature/Model/FlagEvalusationDetails.cs, src/OpenFeature/Model/HookContext.cs, src/OpenFeature/Model/Metadata.cs, src/OpenFeature/Model/ResolutionDetails.cs, src/OpenFeature/NoOpProvider.cs, src/OpenFeature/OpenFeature.cs, src/OpenFeature/OpenFeatureClient.cs, test/OpenFeature.Tests/FeatureProviderExceptionTests.cs, test/OpenFeature.Tests/FeatureProviderTests.cs, test/OpenFeature.Tests/Internal/SpecificationAttribute.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/OpenFeatureEvaluationContextTests.cs, test/OpenFeature.Tests/OpenFeatureHookTests.cs, test/OpenFeature.Tests/OpenFeatureTests.cs, test/OpenFeature.Tests/TestImplementations.cs
It is recommended not to share a namespace and class name to avoid import issues and code like OpenFeature.OpenFeature.Instance.*
Add test case for FeatureClient constructor that tests null provider
=> Update namespace from OpenFeature -> OpenFeature.SDK

src/OpenFeature/Model/FlagEvaluationOptions.cs, test/OpenFeature.Tests/OpenFeatureHookTests.cs
Issue #28
As per requirement 4.5.1 of the specification, the hook hints should be option on the FlagEvaluationOptions constructor.
Should default to empty dictionary
https://github.com/open-feature/spec/blob/1bbbb361952adfa4a94618ffe66e943719be9e50/specification/hooks.md#requirement-451
=> Bug: FlagEvaluationOptions.HookHints should be optional

src/OpenFeature/IFeatureClient.cs, src/OpenFeature/IFeatureProvider.cs, src/OpenFeature/NoOpProvider.cs, src/OpenFeature/OpenFeatureClient.cs, test/OpenFeature.Tests/FeatureProviderTests.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/TestImplementations.cs
As per the recent spec change https://github.com/open-feature/spec/pull/116
- Add GetDoubleValue, GetDoubleDetails and ResolveDoubleValue to FeatureProvider interface
and FeatureClient
- [Breaking change] Rename GetNumberValue, GetNumberDetails to GetIntegerValue, GetIntegerDetails
- Add tests for new methods
=> Feat: Implement seperate methods for integer and double

test/OpenFeature.Tests/OpenFeatureEvaluationContextTests.cs
https://github.com/open-feature/spec/pull/120
Add test to cover new requirement on evaluation context
=> Chore: Evaluation Context must only contain unique values

.config/dotnet-tools.json, .github/workflows/release-package.yml, OpenFeature.SDK.sln
This action will trigger when a new tag is push match {major}.{minor}.{patch}
semver format.
This that need to be setup
-  [x] NUGET_API_KEY needs to be set in github secrets, A key can be generated on nuget.org
=> Chore: Add github action to perform release

src/OpenFeature.SDK/Hook.cs, src/OpenFeature.SDK/OpenFeatureClient.cs
#27 
There is no reason to have the internal IHook interface anymore. C#8
included default implementations on interfaces but since we are on netstandard2.0
we only have access to C#7.3
=> Chore: Remove IHook inteface and just use Hook class

src/OpenFeature.SDK/FeatureProvider.cs, src/OpenFeature.SDK/Model/ResolutionDetails.cs, src/OpenFeature.SDK/NoOpProvider.cs, src/OpenFeature.SDK/OpenFeature.cs, src/OpenFeature.SDK/OpenFeatureClient.cs, test/OpenFeature.SDK.Tests/ClearOpenFeatureInstanceFixture.cs, test/OpenFeature.SDK.Tests/FeatureProviderTests.cs, test/OpenFeature.SDK.Tests/OpenFeatureClientTests.cs, test/OpenFeature.SDK.Tests/OpenFeatureHookTests.cs, test/OpenFeature.SDK.Tests/OpenFeatureTests.cs, test/OpenFeature.SDK.Tests/TestImplementations.cs
Implement provider hook spec https://github.com/open-feature/spec/pull/119
- [Breaking] Remove IFeatureProvider interface in favor of FeatureProvider abstract class
so default implementations can exist
- Make sure Provider hooks are called in the correct order
- Use strick mocking mode so sequence is validated correctly
- Update test cases for provider hooks support
=> Feat: Add support for provider hooks

.config/dotnet-tools.json
This is just to make it easier to install dotnet format if you don't have it globally installed, also ensures the correct version is used.
`dotnet tool restore` will install both dotnet format and minver
=> chore: add dotnet-format to the tools

CONTRIBUTING.md, OpenFeature.SDK.sln, README.md
- Include examples of implmenting hooks and providers
- Include CONTRIBUTING.md
Signed-off-by: Benjamin Evenson <2031163+benjiro@users.noreply.github.com>
=> chore: update readme

README.md, src/OpenFeature.SDK/FeatureProvider.cs, src/OpenFeature.SDK/NoOpProvider.cs, src/OpenFeature.SDK/OpenFeatureClient.cs, test/OpenFeature.SDK.Tests/FeatureProviderTests.cs, test/OpenFeature.SDK.Tests/OpenFeatureClientTests.cs, test/OpenFeature.SDK.Tests/OpenFeatureHookTests.cs, test/OpenFeature.SDK.Tests/TestImplementations.cs
#51
As per spec 0.4 remove flag evaluation option from the provider
- Update FeatureProvider
- Update doco
=> Removed evaluation options from provider

src/OpenFeature.SDK/FeatureProvider.cs, src/OpenFeature.SDK/IFeatureClient.cs, src/OpenFeature.SDK/Model/EvaluationContext.cs, src/OpenFeature.SDK/Model/Structure.cs, src/OpenFeature.SDK/Model/Value.cs, src/OpenFeature.SDK/NoOpProvider.cs, src/OpenFeature.SDK/OpenFeatureClient.cs, test/OpenFeature.SDK.Tests/FeatureProviderTests.cs, test/OpenFeature.SDK.Tests/OpenFeature.SDK.Tests.csproj, test/OpenFeature.SDK.Tests/OpenFeatureClientTests.cs, test/OpenFeature.SDK.Tests/OpenFeatureEvaluationContextTests.cs, test/OpenFeature.SDK.Tests/OpenFeatureHookTests.cs, test/OpenFeature.SDK.Tests/StructureTests.cs, test/OpenFeature.SDK.Tests/TestImplementations.cs, test/OpenFeature.SDK.Tests/ValueTests.cs
Born from the discussions in #25 and https://github.com/open-feature/java-sdk/issues/50
- Adds `Structure` type which represents JSON data
- Adds `Value` wrapper class that houses the supported types (Structure, List, bool, int, double, Value - note ints are stored and doubles, and rounded when returned)
- `EvaluationContext` exposes methods to interact with its underlying keyvalue pairs of string, `Value`
- Update interfaces to use `Structure` instead of generics
=> Rework EvaluationContext to use Structure type

src/OpenFeature.SDK/OpenFeatureClient.cs, test/OpenFeature.SDK.Tests/OpenFeatureClientTests.cs
Adding this for consistency with other SDKs.
=> Add setter for context

src/OpenFeature.SDK/FeatureProvider.cs, src/OpenFeature.SDK/IFeatureClient.cs, src/OpenFeature.SDK/Model/Value.cs, src/OpenFeature.SDK/NoOpProvider.cs, src/OpenFeature.SDK/OpenFeatureClient.cs, test/OpenFeature.SDK.Tests/FeatureProviderTests.cs, test/OpenFeature.SDK.Tests/OpenFeatureClientTests.cs, test/OpenFeature.SDK.Tests/OpenFeatureEvaluationContextTests.cs, test/OpenFeature.SDK.Tests/OpenFeatureHookTests.cs, test/OpenFeature.SDK.Tests/StructureTests.cs, test/OpenFeature.SDK.Tests/TestImplementations.cs, test/OpenFeature.SDK.Tests/ValueTests.cs
A c# flavored version of: https://github.com/open-feature/java-sdk/pull/65. I hope these are the last breaking changes before a 1.0rc.
- add object constructor and accessor to `Value`
- use `Value` instead of `Structure` in object resolver (https://github.com/open-feature/spec/issues/138#issuecomment-1241202093)
=> BREAKING: add structure->value, object value constructor

src/OpenFeature.SDK/Model/EvaluationContext.cs
When working on a provider I noticed that there were a number of empty documentation comments in the EvaluationContext.
In addition to filling those out I thought it would be nice if it was clear what the behavior was regarding missing keys, duplicate keys, etc.
=> Document EvaluationContext members.

.github/workflows/release.yml
=> fix: substitute version number into filename when pushing package

src/OpenFeatureSDK/Constant/ErrorType.cs, src/OpenFeatureSDK/Error/FeatureProviderException.cs, src/OpenFeatureSDK/Extension/ResolutionDetailsExtensions.cs, src/OpenFeatureSDK/Model/FlagEvaluationDetails.cs, src/OpenFeatureSDK/Model/ResolutionDetails.cs, src/OpenFeatureSDK/OpenFeatureClient.cs, test/OpenFeatureSDK.Tests/FeatureProviderExceptionTests.cs, test/OpenFeatureSDK.Tests/FeatureProviderTests.cs, test/OpenFeatureSDK.Tests/OpenFeatureClientTests.cs
Addresses: https://github.com/open-feature/dotnet-sdk/issues/71
Extend the `ErrorType` to include `INVALID_CONTEXT` and `TARGETING_KEY_MISSING`.
Change the `ErrorType` in `FlagEvaluationDetails` to an enum.
Update the `FeatureProviderException` to have an enumerated code. Use `message` for the `error message`.
Update tests, and update specification references in tests.
=> feat!: ErrorType as enum, add ErrorMessage string

src/OpenFeatureSDK/FeatureProvider.cs, src/OpenFeatureSDK/Model/FlagEvaluationOptions.cs, src/OpenFeatureSDK/OpenFeature.cs, src/OpenFeatureSDK/OpenFeatureClient.cs, test/OpenFeatureSDK.Tests/OpenFeatureClientTests.cs, test/OpenFeatureSDK.Tests/OpenFeatureHookTests.cs, test/OpenFeatureSDK.Tests/OpenFeatureTests.cs, test/OpenFeatureSDK.Tests/TestImplementations.cs
- Change storage type of global hooks to a concurrent stack.
- Should be able to add and remove from this without locking,
- Protect references used from multiple threads with a Read/Write lock.
- Change read only collection types to immutable collection types.
- Readonly collections are just views into existing mutable collections. So they are still subject to the same modification problems. Immutable collections are supposed to be fixed and unchanging. Considering they are an interface you could still violate this constraint, but it is less likely.
Related to: https://github.com/open-feature/dotnet-sdk/issues/56
=> feat!: Thread safe hooks, provider, and context

build/Common.props
When other dependencies are referring to Microsoft.Extensions.Logging library above 6.0 nuget will be unable to resolve and cause a mismatch issue.
We should support anything above 2.0
=> fix: correct version range on logging

src/OpenFeature/IFeatureClient.cs, src/OpenFeature/OpenFeatureClient.cs
Signed-off-by: Chris Donnelly <cdonnellytx@users.noreply.github.com>
- Exposes the `IFeatureClient` interface to consumers by making it public.
- Pulls up the XMLDoc from the concrete class to the interface, filling in gaps (e.g., the interface-level docs) from the Java SDK.
This allows consumers using dependency injection to properly create a mock of the feature client.  Currently, the exposed `FeatureClient` class is sealed, therefore making it extremely difficult ([though not impossible](https://stackoverflow.com/a/12187583)) for consumers to mock in parallel without side-effects.
Consider
```csharp
public class MyService
{
private readonly FeatureClient _featureClient;
public MyService(FeatureClient featureClient, ...)
{
_featureClient = featureClient;
}
public async Task<int> …
```
=> feat: Make IFeatureClient interface public.

README.md, src/OpenFeature/Api.cs, src/OpenFeature/Constant/ErrorType.cs, src/OpenFeature/Constant/Reason.cs, src/OpenFeature/FeatureProvider.cs, src/OpenFeature/Hook.cs, src/OpenFeature/Model/EvaluationContext.cs, src/OpenFeature/Model/FlagEvaluationDetails.cs, src/OpenFeature/Model/FlagEvaluationOptions.cs, src/OpenFeature/Model/HookContext.cs, src/OpenFeature/Model/ResolutionDetails.cs, test/OpenFeature.Tests/FeatureProviderTests.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/OpenFeatureEvaluationContextTests.cs, test/OpenFeature.Tests/OpenFeatureHookTests.cs, test/OpenFeature.Tests/OpenFeatureTests.cs
Signed-off-by: Chris Donnelly [cdonnellytx@users.noreply.github.com](mailto:cdonnellytx@users.noreply.github.com)
- Fixes broken spec links in the XML documentation
- Fixes spec references in the tests (both code and description)
- Adds one additional test to cover 4.4.5 "after" phase
Partial fix for #84 (skips v0.5.1, goes to v0.5.2).
I started this because I found the `see` links were broken.  Then I realized I should probably fix the specification attribute numbers.  Then I added one test.  Stopping there :)
These are the remaining spec items that I saw that do not have tests labeled:
- **1.1.6** The client creation function MUST NOT throw, or otherwise abnormally terminate.
- **1.4.12** In cases of abnormal execution, the `evaluation details` structure's `error message` field MAY …
=> docs: fix broken links

src/OpenFeature/Error/FeatureProviderException.cs, src/OpenFeature/Error/FlagNotFoundException.cs, src/OpenFeature/Error/GeneralException.cs, src/OpenFeature/Error/InvalidContextException.cs, src/OpenFeature/Error/ParseErrorException.cs, src/OpenFeature/Error/ProviderNotReadyException.cs, src/OpenFeature/Error/TargetingKeyMissingException.cs, src/OpenFeature/Error/TypeMismatchException.cs
Signed-off-by: Valentinas <31697821+valentk777@users.noreply.github.com>
In this PR, I created a separate class for each error type.
Fixes https://github.com/open-feature/dotnet-sdk/issues/110
=> feat: split errors to classes by types

CONTRIBUTING.md, OpenFeature.sln, build/Common.tests.props, src/OpenFeature/OpenFeature.csproj, test/OpenFeature.Benchmarks/OpenFeature.Benchmarks.csproj, test/OpenFeature.Benchmarks/OpenFeatureClientBenchmarks.cs, test/OpenFeature.Benchmarks/Program.cs
Signed-off-by: Valentinas <31697821+valentk777@users.noreply.github.com>
Added initial API benchmark (only for a few functions). Later we can increase the functions count by covering hooks as well. 
Adds initial project to run benchmarks for API part.
Fixes #22
I added the result table here.
=> test: add initial api benchmarks

src/OpenFeature/Error/FlagNotFoundException.cs, src/OpenFeature/Error/GeneralException.cs, src/OpenFeature/Error/InvalidContextException.cs, src/OpenFeature/Error/ParseErrorException.cs, src/OpenFeature/Error/ProviderNotReadyException.cs, src/OpenFeature/Error/TargetingKeyMissingException.cs, src/OpenFeature/Error/TypeMismatchException.cs
Exclude standard error from code coverage
There is no point in adding unit tests around exceptions that aren't being used in the core library.
These were introduced under https://github.com/open-feature/dotnet-sdk/issues/110
N/A
N/A
N/A
=> chore: Exclude standard error from code coverage

src/OpenFeature/Api.cs, src/OpenFeature/OpenFeatureClient.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/OpenFeatureTests.cs, test/OpenFeature.Tests/TestImplementations.cs
Adds support for mapping name clients to a given provider.
- Preserves backward compatibility with existing clients
Refs: Refs https://github.com/open-feature/ofep/pull/56
Fixes: https://github.com/open-feature/dotnet-sdk/issues/131
N/A
Testing is covered by the unit tests added in the PR
=> feat: Support for name client to given provider

build/Common.props
remove max System.Collections.Immutable version
fixes: https://github.com/open-feature/dotnet-sdk/issues/136
=> fix: max System.Collections.Immutable version ++

test/OpenFeature.Tests/OpenFeatureHookTests.cs
- Replaces Moq with NSubstitute for `When_Error_Occurs_In_Before_Hook_Should_Return_Default_Value` test
Fixes #140 
I am trying to figure out the sequence for the tests there are still missing. See [#140](https://github.com/open-feature/dotnet-sdk/pull/141#issuecomment-1674337623) for more details
Missing only:
```
Hook_Hints_May_Be_Optional
When_Error_Occurs_In_After_Hook_Should_Invoke_Error_Hook
```
CI should pass :)
=> test: Replace Moq with NSubstitute

test/OpenFeature.Tests/OpenFeature.Tests.csproj, test/OpenFeature.Tests/OpenFeatureHookTests.cs
Update the following test to use NSubstitute
Hook_Hints_May_Be_Optional
When_Error_Occurs_In_After_Hook_Should_Invoke_Error_Hook
Fixes https://github.com/open-feature/dotnet-sdk/issues/140
N/A
N/A
N/A
=> test: Replace remaining Moq with NSubstitute

src/OpenFeature/OpenFeatureClient.cs
-Added configure await false to avoid deadlocks when executing synchronously from client applications. 
Fixes [#149](https://github.com/open-feature/dotnet-sdk/issues/149)
I published a Nuget package locally and confirmed this fixes the deadlock issue that I'm seeing in my project.
=> fix: deadlocks in client applications

.editorconfig, build/Common.props, test/OpenFeature.Benchmarks/OpenFeatureClientBenchmarks.cs, test/OpenFeature.Tests/FeatureProviderTests.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/OpenFeatureHookTests.cs
- Enable dotnet anaylzers
- Ignore rule in benchmarks/tests
Stop https://github.com/open-feature/dotnet-sdk/issues/149 happening again in the future
N/A
N/A
N/A
=> feat: Add dx to catch ConfigureAwait(false)

README.md, release-please-config.json
- Updates README.md to follow new template
Fixes [#145 ](https://github.com/open-feature/dotnet-sdk/issues/145)
As far as I understood, the *Eventing* feature and the *Shutdown* feature haven't been implemented yet
=> docs: update README.md

README.md
- add placeholder eventing and shutdown sections
Addresses a linting issue discovered in a documentation PR.
PR: https://github.com/open-feature/openfeature.dev/pull/248
Lint output: https://github.com/open-feature/openfeature.dev/actions/runs/6488117185/job/17619868654?pr=248
Update the documentation PR.
=> chore: add placeholder eventing and shutdown sections

.github/workflows/ci.yml, .github/workflows/e2e.yml, build/Common.tests.props
- https://github.com/Tyrrrz/GitHubActionsTestLogger
See: open-feature/dotnet-sdk-contrib#134
___
_screencaps via [Tyrrrz/GitHubActionsTestLogger](https://github.com/Tyrrrz/GitHubActionsTestLogger#screenshots)_
=> chore: Add GitHub Actions logger for CI

.github/workflows/ci.yml, .github/workflows/code-coverage.yml, .github/workflows/dotnet-format.yml, .github/workflows/e2e.yml, .github/workflows/release.yml, global.json, src/OpenFeature/OpenFeature.csproj, test/OpenFeature.Benchmarks/OpenFeature.Benchmarks.csproj, test/OpenFeature.E2ETests/OpenFeature.E2ETests.csproj, test/OpenFeature.Tests/OpenFeature.Tests.csproj
As a consumer of the OpenFeature SDK, I want `OpenFeature.dll` to be built and tested against all of the [supported TFMs](https://learn.microsoft.com/lifecycle/products/microsoft-net-and-net-core) that my projects might encounter in the wild.
This PR:
1. Updates the `global.json` to `8.0.100`
2. Updates workflows using _only_ `7.0.x` to instead resolve based on `global.json`
3. Updates the project(s) TFMs to include `net6.0`, `net7.0`, and `net8.0`
- `net6.0` is EOL in `2024-11-12`
- `net7.0` is EOL in `2024-05-14`
Fixes: #160, #169
=> refactor: Add TFMs for net{6,7,8}.0

build/Common.props
Fixes: #170
See: #136, #137, #170 
___
_Anticipate similar arguments/discussion as in #137, but opening as a companion to #170 because this is causing me real-world grief today 🙃_
=> fix: Remove upper-bound version constraint from SCI

src/OpenFeature/OpenFeature.csproj
Ran across this while working on open-feature/dotnet-sdk-contrib#127, but tldr; libraries don't need the implementation package, so reduce to the abstractions package to remove transitive dependencies on:
- `Microsoft.Extensions.DependencyInjection`
- `Microsoft.Extensions.Options`
- (and a few others depending on the TFM)
=> chore: Reduce dependency on MEL -> MELA

src/OpenFeature/Api.cs, src/OpenFeature/OpenFeatureClient.cs, test/OpenFeature.Tests/OpenFeatureHookTests.cs
Stumbled into this one while working on #186 (while working on #181).
See: dotnet/runtime#62121, dotnet/runtime#62126
=> fix: Fix ArgumentOutOfRangeException for empty hooks

src/OpenFeature/Model/ClientMetadata.cs, src/OpenFeature/Model/FlagEvaluationDetails.cs, src/OpenFeature/Model/FlagEvaluationOptions.cs, src/OpenFeature/Model/HookContext.cs, src/OpenFeature/Model/ResolutionDetails.cs, src/OpenFeature/NoOpProvider.cs, src/OpenFeature/ProviderRepository.cs
- This class seals some of the classes that are not being inherited.
- If you think of a class that should be allowed inheritance, please block this PR so we can remove it
- sealing classes is a good practice. Check this article: https://www.codeproject.com/Articles/239939/Csharp-Tweaks-Why-to-use-the-sealed-keyword-on-cla
=> chore: Adding sealed keyword to classes

build/Common.props, src/OpenFeature/Api.cs, src/OpenFeature/EventExecutor.cs, src/OpenFeature/OpenFeature.csproj, src/OpenFeature/OpenFeatureClient.cs, src/OpenFeature/ProviderRepository.cs, test/OpenFeature.Tests/OpenFeatureTests.cs
Previously, we shutdown the consumer thread causing any reuse of the Api to block on the second event emitted to the event executor.
Fixes: #186
___
Stumbled into this one while working on #181 in which I've added unit tests that each setup their own independent `IHost` and then dispose of it at the conclusion of each test case.
But since the `Api.Instance` is inherently static/shared, subsequent test cases were observed blocking until CI timeout occurred.
This PR could reasonably be criticized for going a step too far by introducing a new dependency on `Microsoft.Bcl.AsyncInterfaces`, but I decided to propose it anyways on the basis that  `Microsoft.Bcl.AsyncInterfaces` is a transitive dependency of `Microsoft.Extensions.DependencyInjection.Abstractions` which itself is a transitive …
=> fix: More robust shutdown/cleanup/reset

.github/workflows/release.yml, build/Common.prod.props
Ran across this while working on open-feature/dotnet-sdk-contrib#127, and tldr; if there's more than one project under `src/`, having the `<PackageId>` hard-coded in `build/Common.prod.props` causes MSBuild to panic.
There are two options to fix this:
1. ```diff
- <PackageId>OpenFeature</PackageId>
+ <PackageId>$(MSBuildProjectName)</PackageId>
```
2. ```diff
- <PackageId>OpenFeature</PackageId>
```
Since NuGet defaults `PackageId` to the assembly name, I'm opting for (2), but if I've overlooked some nuance/custom build steps that require setting `PackageId` explicitly, then we could just as well fallback to (1).
```console
$ dotnet restore
Determining projects to restore...
dotnet/sdk/7.0.404/NuGet.targets(158,5): error : Ambiguous project name 'OpenFeature'. …
```
=> chore: Fix props to support more than one project

.github/workflows/ci.yml, build/Common.prod.props, build/Common.props
| `GITHUB_REF`     | version format                                     |
|------------------|----------------------------------------------------|
| `refs/heads/*`   | `#.#.#-ci.{%Y%m%d}T{%H%M%S}+sha.${GITHUB_SHA:0:9}` |
| `refs/pull/*`    | `#.#.#-pr.{%Y%m%d}T{%H%M%S}+sha.${GITHUB_SHA:0:9}` |
See: #54, open-feature/dotnet-sdk-contrib#134
Closes: #54
=> chore: Add support for GitHub Packages

src/OpenFeature/Api.cs, test/OpenFeature.E2ETests/Steps/EvaluationStepDefinitions.cs, test/OpenFeature.Tests/ClearOpenFeatureInstanceFixture.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/OpenFeatureEventTests.cs, test/OpenFeature.Tests/OpenFeatureHookTests.cs, test/OpenFeature.Tests/OpenFeatureTests.cs, test/OpenFeature.Tests/ProviderRepositoryTests.cs
This PR makes the breaking change [here](https://github.com/open-feature/dotnet-sdk/pull/158#discussion_r1378120046) non breaking, by adding a new method instead. This means our pending release will no longer be breaking.
This will allow us to release all the pending .NET work, without merging https://github.com/open-feature/dotnet-sdk/pull/184. I like the idea of https://github.com/open-feature/dotnet-sdk/pull/184, but I think I'd like us all to take some time to discuss exactly what we expect the `cancellationToken` to do in all circumstances (what should the SDK do on SDK methods like `init()/shutdown()`?, and what should providers do?).
I think buys us some without sacrificing too much, and we can release a 2.0.0 in the coming weeks.
Interested to hear the opinion of others.
=> chore: revert breaking setProvider

build/Common.prod.props, build/Common.props, src/Directory.Build.targets
- https://learn.microsoft.com/dotnet/core/compatibility/sdk/8.0/source-link
> ## [Using Source Link in .NET projects](https://github.com/dotnet/sourcelink?tab=readme-ov-file#using-source-link-in-net-projects)
> 
> Starting with .NET 8, Source Link for the following source control providers is included in the .NET SDK and enabled by default:
> - [GitHub](http://github.com) or [GitHub Enterprise](https://enterprise.github.com/home) 
> - [Azure Repos](https://azure.microsoft.com/en-us/services/devops/repos) git repositories (formerly known as Visual Studio Team Services)
> - [GitLab](https://gitlab.com) 12.0+ (for older versions see [GitLab settings](#gitlab))
> - [Bitbucket](https://bitbucket.org/) 4.7+ (for older versions see [Bitbucket settings](#bitbucket))
> 
> If your project uses .NET …
=> chore: SourceLink is built-in for .NET SDK 8.0.100+

OpenFeature.sln
- This PR fixes an issue related to opening the project in VSCode.
See log output here: 
```
Failed at 'Open a solution with environment service' (5ms) with error: Error: An item with the same key has already been added. Key: 90e7ead3-251e-4490-af78-e758e33518e5
Failed at 'Open a solution' (8ms) with error: SolutionOpenError: Run into errors while opening the solution: Error: An item with the same key has already been added. Key: 90e7ead3-251e-4490-af78-e758e33518e5
Failed to open solution SolutionOpenError: Run into errors while opening the solution: Error: An item with the same key has already been added. Key: 90e7ead3-251e-4490-af78-e758e33518e5
```
Just open VSCode and check it's working again.
=> build: Update OpenFeature.sln

OpenFeature.sln
Follow up to #202 because I realized a moment too late that my suggestion inadvertently dropped an xref for the original GUID we we're trying to un-dupe.
While I'm in here, adding some additional sln folders so I don't have to keep flipping back and forth from sln view <-> filesystem view. _(Hoping these won't be controversial? But open to pulling back on some of this if it rubs anyone the wrong way.)_
See: #202
=> chore: More sln cleanup

.github/workflows/ci.yml, .github/workflows/code-coverage.yml, .github/workflows/e2e.yml, .github/workflows/release.yml, CONTRIBUTING.md, nuget.config
Follows #173 and open-feature/dotnet-sdk-contrib#134 to synchronize `ci.yml` between both repos.
```console
$ diff dotnet-sdk{,-contrib}/.github/workflows/ci.yml
```
____
Story here is a little convoluted, but basically this repo already had the linux and windows tests in one workflow, so for #173 I was able to just condition the new `packaging` job on both `unit-tests-linux` and `unit-tests-windows` completing successfully.
However, prior to open-feature/dotnet-sdk-contrib#134, the contrib repo had separate workflow files for its respective linux and windows tests, so as part of open-feature/dotnet-sdk-contrib#134, I merged those separate workflows into one workflow and, at the same time, rewrote them to use a job matrix.
For PR consistency, I almost included the same job matrix update …
=> chore: Sync ci.yml with contrib repo

Directory.Packages.props
Very silly, had this right in my internal projects and decided to "simplify" it when I reimplemented here 🤦🤦🤦
tldr; NuGet analyzers run over the `Directory.Packages.props` file without validating whether a given `PackageVersion` is used in a given TFM, so the analyzer pops even though the build is happy. I'm still a little confused as to why I can't repro locally, but probably caching, so "un-simplifying" my earlier oops and all should hopefully work as intended going forward.
See: #165, #196, #219, #220
H/T @CommCody
=> fix: Fix NU1009 reference assembly warning

README.md
- fixes confusing link in the readme
Fixes #228
This will automatically be included in the OpenFeature docs once this PR is merged.
=> docs: fix hook ecosystem link

Directory.Packages.props, test/OpenFeature.Tests/OpenFeatureTests.cs, test/OpenFeature.Tests/StructureTests.cs, test/OpenFeature.Tests/TestUtilsTest.cs, test/OpenFeature.Tests/ValueTests.cs
Upgrade all test deps
- Autofixture 4.17 -> 4.18.1
- coverlet 3.1.2 -> 6.0.0
- FluentAssertions 6.7.0 -> 6.12.0
- MSN.Test.Sdk 17.2.0 -> 17.9.0
- NSubstitue 5 -> 5.1
- FlagD Provider 0.1.5 -> 0.1.8
- Xunit 2.4.1 -> 2.6.6
Fixes #197
=> test: Upgrade test deps

test/OpenFeature.Tests/Providers/Memory/InMemoryProviderTests.cs
Supress ConfigureAwait for unit tests as its not relevant, cleanup warnings
=> test: Fix up xunit warnings

.editorconfig, build/Common.props
A follow on from the previous PR that removed unused using, this will make sure it won't occur in the future. https://github.com/open-feature/dotnet-sdk/pull/240#issuecomment-1956892758
- Enforce code styles on build
- Error on unused usings
- Apply workaround for IDE0005 rule
Fixes https://github.com/open-feature/dotnet-sdk/pull/240#issuecomment-1956892758
=> chore: Enforce coding styles on build

README.md
- bump spec version badge to 0.7.0
Fixes #193
=> chore: bump spec version badge

build/Common.props, src/OpenFeature/OpenFeature.csproj
- simplify the `InternalsVisibleTo` usage
- cleanup msbuild condition
- remove unnecessary dependencies
=> chore(deps): Project file cleanup and remove unnecessary dependencies

src/OpenFeature/OpenFeatureClient.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs
- Add missing error message when an error occurred
Fixes #255
=> fix: Add missing error message when an error occurred

src/OpenFeature/OpenFeatureClient.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs
Backport of https://github.com/open-feature/dotnet-sdk/pull/256
=> fix: Add missing error message when an error occured

.github/workflows/dotnet-format.yml
- This PR changes the code formatter we currently use to the new built-in in the SDK. See https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-format
- We should now use this tool since it is now shipped as part of the dotnet SDK, removing the need to install an external one.
- As pointed out in the chat, this build runs in parallel and is relatively fast. I will enable all PRs instead of those focusing on changes to .cs files.
=> ci: Change dotnet formatter

README.md, src/OpenFeature/Api.cs, src/OpenFeature/EventExecutor.cs, src/OpenFeature/FeatureProvider.cs, src/OpenFeature/Hook.cs, src/OpenFeature/IFeatureClient.cs, src/OpenFeature/Model/EvaluationContext.cs, src/OpenFeature/NoOpProvider.cs, src/OpenFeature/OpenFeatureClient.cs, src/OpenFeature/ProviderRepository.cs, src/OpenFeature/Providers/Memory/InMemoryProvider.cs, test/OpenFeature.Benchmarks/OpenFeatureClientBenchmarks.cs, test/OpenFeature.E2ETests/Steps/EvaluationStepDefinitions.cs, test/OpenFeature.Tests/FeatureProviderTests.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/OpenFeatureEventTests.cs, test/OpenFeature.Tests/OpenFeatureHookTests.cs, test/OpenFeature.Tests/OpenFeatureTests.cs, test/OpenFeature.Tests/ProviderRepositoryTests.cs, test/OpenFeature.Tests/Providers/Memory/InMemoryProviderTests.cs, test/OpenFeature.Tests/TestImplementations.cs, test/OpenFeature.Tests/TestUtilsTest.cs
This PR is a combination of https://github.com/open-feature/dotnet-sdk/pull/184 and https://github.com/open-feature/dotnet-sdk/pull/185. Changes include:
- adding cancellation tokens
- in all cases where async operations include side-effects (`setProviderAsync`, `InitializeAsync`, I've specified in the in-line doc that the cancellation token's purpose is to cancel such side-effects - so setting a provider and canceling that operation still results in that provider's being set, but async side-effect should be cancelled. I'm interested in feedback here, I think we need to consider the semantics around this... I suppose the alternative would be to always ensure any state changes only occur after async side-effects, if they weren't cancelled beforehand. 
- adding "Async" suffix to all async …
=> feat!: add CancellationTokens, ValueTasks hooks

src/OpenFeature/Api.cs, src/OpenFeature/Constant/ErrorType.cs, src/OpenFeature/Constant/ProviderStatus.cs, src/OpenFeature/Error/ProviderFatalException.cs, src/OpenFeature/Error/ProviderNotReadyException.cs, src/OpenFeature/EventExecutor.cs, src/OpenFeature/FeatureProvider.cs, src/OpenFeature/IFeatureClient.cs, src/OpenFeature/Model/ProviderEvents.cs, src/OpenFeature/OpenFeatureClient.cs, src/OpenFeature/ProviderRepository.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/OpenFeatureEventTests.cs, test/OpenFeature.Tests/OpenFeatureTests.cs, test/OpenFeature.Tests/ProviderRepositoryTests.cs, test/OpenFeature.Tests/TestImplementations.cs
This PR implements a few things from spec 0.8.0:
- implements internal provider status (already implemented in JS)
- the provider no longer updates its status to READY/ERROR, etc after init (the SDK does this automatically)
- the provider's state is updated according to the last event it fired
- adds `PROVIDER_FATAL` error and code
- adds "short circuit" feature when evaluations are skipped if provider is `NOT_READY` or `FATAL`
- removes some deprecations that were making the work harder since we already have pending breaking changes.
Fixes: https://github.com/open-feature/dotnet-sdk/issues/250
=> feat!: internally maintain provider status

src/OpenFeature/Api.cs, src/OpenFeature/Constant/Reason.cs, src/OpenFeature/Error/ProviderFatalException.cs, src/OpenFeature/EventExecutor.cs, src/OpenFeature/FeatureProvider.cs, src/OpenFeature/Model/EvaluationContextBuilder.cs, src/OpenFeature/Model/FlagEvaluationOptions.cs, src/OpenFeature/Model/ImmutableMetadata.cs, src/OpenFeature/Model/Value.cs, src/OpenFeature/OpenFeatureClient.cs, src/OpenFeature/ProviderRepository.cs, src/OpenFeature/Providers/Memory/Flag.cs, src/OpenFeature/Providers/Memory/InMemoryProvider.cs, test/OpenFeature.Benchmarks/OpenFeatureClientBenchmarks.cs, test/OpenFeature.E2ETests/Steps/EvaluationStepDefinitions.cs, test/OpenFeature.Tests/OpenFeatureTests.cs, test/OpenFeature.Tests/TestImplementations.cs
This PR fixes some of the warnings and typos that I recently found.
More interestingly, it addresses these issues:
- Missing the `.this`
- Usage of `ILogger` vs `Source generator log`
- `const` vs `static`
- Fix nullability for some methods and properties.
And a few more changes.
We need to do more cleanup tasks.
All of these changes are recommended by the IDE and "tested" by the compiler when it executes.
=> chore: cleanup code

.github/workflows/ci.yml, .github/workflows/code-coverage.yml, .github/workflows/e2e.yml, .github/workflows/release.yml, src/OpenFeature/OpenFeature.csproj, test/OpenFeature.Benchmarks/OpenFeature.Benchmarks.csproj, test/OpenFeature.E2ETests/OpenFeature.E2ETests.csproj, test/OpenFeature.Tests/OpenFeature.Tests.csproj
.net7 was EOL on May 14, 2024
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
=> feat: Drop net7 TFM

src/OpenFeature/Extension/ResolutionDetailsExtensions.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs
When converting the ResolutionDetails to FlagEvalutionDetails we aren't passing the ImmutableMetadata to the new object.
Fixes [#281](https://github.com/open-feature/dotnet-sdk/issues/281)
This PR is done on a common merge base so we can merge it into v1 as well
N/A
Unit test added to covert the missing test case
=> fix: Should map metadata when converting from ResolutionDetails to FlagEvaluationDetails

src/OpenFeature/Model/EvaluationContext.cs, src/OpenFeature/Model/EvaluationContextBuilder.cs, test/OpenFeature.Tests/OpenFeatureEvaluationContextTests.cs
Use the internal dictionary for the `targetingKey`.
This is non-breaking from a compiler perspective. It could result in some behavioral changes, but IMO they are largely desirable.
Fixes: https://github.com/open-feature/dotnet-sdk/issues/235
=> feat: back targetingKey with internal map

README.md, src/OpenFeature/Api.cs, src/OpenFeature/ProviderRepository.cs, test/OpenFeature.Benchmarks/OpenFeatureClientBenchmarks.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/OpenFeatureEventTests.cs, test/OpenFeature.Tests/OpenFeatureHookTests.cs, test/OpenFeature.Tests/OpenFeatureTests.cs
Uses "domain" terminology instead of "client name / named client".
Fixes: https://github.com/open-feature/dotnet-sdk/issues/249
I believe with this, we are able to release a 2.0
=> feat!: domain instead of client name

src/OpenFeature/Providers/Memory/InMemoryProvider.cs, test/OpenFeature.Tests/Providers/Memory/InMemoryProviderTests.cs
I was doing an audit before the release and found this one method could use a suffix update.
=> chore: in-memory UpdateFlags to UpdateFlagsAsync

test/OpenFeature.Tests/ClearOpenFeatureInstanceFixture.cs
- It fixes an issue where the context sometimes needs to be cleared correctly.
- It should eliminate any further race conditions in the unit tests.
Following an investigation on xUnit shared contexts, I found we should use `IDisposable` to clear data between tests. See https://xunit.net/docs/shared-context for reference.
=> fix: Fix unit test clean context 

.github/workflows/code-coverage.yml
Correct syntax inconsistencies in the GitHub Actions workflow file for improved readability and consistency.
=> fix: Fix action syntax in workflow configuration

src/OpenFeature/OpenFeatureClient.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/TestImplementations.cs
- When a Flag evaluation fails without throwing an exception, the registered error hooks are invoked, and the after hooks are not invoked. 
Fixes #307 
`test/OpenFeature.Tests/OpenFeatureClientTests#When_Error_Is_Returned_From_Provider_Should_Not_Run_After_Hook_But_Error_Hook` verifies the behaviour
=> feat: Support Returning Error Resolutions from Providers

README.md
A recent change in the markdown link rules made multi-line links a violation of MD039.
https://github.com/DavidAnson/markdownlint/commit/a6cf08dfc654e5b7610cbb153d423d6a0f3b7907
This is impacting the doc updater.
https://github.com/open-feature/openfeature.dev/actions/runs/12348450303/job/34457301528?pr=872
=> docs: disable space in link text lint rule

src/OpenFeature/Api.cs, test/OpenFeature.Tests/ClearOpenFeatureInstanceFixture.cs
- Changes the way we currently reset the Api between unit tests. This approach should be safer since it calls the official `Shutdown`, and when we call the API again, all the resources are reset.
Check for more details: https://xunit.net/docs/shared-context#:~:text=For%20context%20cleanup%2C%20add%20the%20IDisposable%20interface%20to,call%20IAsyncDisposable%20%28it%20is%20planned%20for%20xUnit%20v3%29.
=> fix: Adding Async Lifetime method to fix flaky unit tests

README.md, src/OpenFeature/Hook.cs, src/OpenFeature/OpenFeatureClient.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs, test/OpenFeature.Tests/OpenFeatureHookTests.cs, test/OpenFeature.Tests/TestImplementations.cs
This pull request includes several changes to improve the handling of flag evaluation details and error handling in the OpenFeature library. The most important changes include modifying hook methods to accept `FlagEvaluationDetails` as a parameter, updating the `EvaluateFlagAsync` method to handle provider errors more gracefully, and adjusting the corresponding unit tests to reflect these changes.
Fixes #328 
* [`src/OpenFeature/Hook.cs`](diffhunk://#diff-d69e6a4b3c0fb22dcb05a1104cd353a597bc8f54bb29c458ed41d394d8f1c12aL34-R35): Modified the `FinallyAsync` methods to accept `FlagEvaluationDetails` as a parameter. [[1]](diffhunk://#diff-d69e6a4b3c0fb22dcb05a1104cd353a597bc8f54bb29c458ed41d394d8f1c12aR76-R83)
* [`src/OpenFeature/Hook.cs`](diffhunk://#diff-d69e6a4b3c0fb22dcb05a1104cd353a597bc8 …
=> feat: Add evaluation details to finally hook stage

.github/workflows/ci.yml, .github/workflows/release.yml
- Adds release configuration parameter to `dotnet pack`
Fixes #345 
Using dotnet publish or dotnet pack compiles assemblies in debug mode unless you explicitly specify -c release. So the package is compiled without optimizations.
This is failing my builds which check for debug assemblies.
More info: https://garcia.in/posts/2021/pitfalls-of-unoptimized-nuget-packages/
=> ci: dotnet pack release build

README.md
- Addresses issue with the README documentation for Dependency Injection Providers.
Fixes #349
=> fix: Fix issue with DI documentation

.github/workflows/dco-merge-group.yml
- add dco workaround
Relates to #356
The DCO bot doesn't support merge queues. This is a workaround that we're using in other repos.
=> ci: add dco workaround

test/OpenFeature.Tests/Hooks/LoggingHookTests.cs
I noticed when I ran the LoggingHook unit tests on a WSL Ubuntu instance the some tests fails due to new line characters. It appears I never normalized or excluded newline characters when asserting equal
I also removed the `Assert.Contains` snippets as the content and layout of the log message is asserted in the other tests. This Assert method does not have an overload for ignoring new line characters
I assume the GitHub CI runner may be ignore the line endings by default?
=> fix: Address issue with newline characters when running Logging Hook Unit Tests on linux

.github/workflows/release.yml
- updates the release please repo (see [here](https://github.com/google-github-actions/release-please-action))
- specify required permissions for each release stage
I copied most of this change from another repo. Please double-check that I didn't miss anything obvious. Thanks!
=> chore: update release please repo, specify action permissions

src/OpenFeature.DependencyInjection/OpenFeature.DependencyInjection.csproj, src/OpenFeature/FeatureProvider.cs, src/OpenFeature/OpenFeature.csproj
simplify and unify the InternalsVisibleTo usage
=> refactor: simplify the InternalsVisibleTo usage

src/OpenFeature.Hosting/FeatureLifecycleStateOptions.cs, src/OpenFeature.Hosting/OpenFeatureBuilderExtensions.cs
- feat: update FeatureLifecycleStateOptions.StopState default to Stopped
- refactor: remove the default options setup since it's same as default value, no need to configure
Fixes #410
=> feat: update FeatureLifecycleStateOptions.StopState default to Stopped

Directory.Packages.props
This pull request includes updates to the `Directory.Packages.props` file to centralize and manage package versions more effectively, particularly for Microsoft Extensions packages.
Key changes include:
* Added a new property `MicrosoftExtensionsVersion` with a default value of `8.0.0` and a conditional value of `9.0.0` for `net9.0` target framework.
* Updated `PackageVersion` elements to use the new `MicrosoftExtensionsVersion` property instead of hardcoded version numbers.
Fixes #424 
I tried to follow the https://github.com/App-vNext/Polly approach to determining the dependencies we should bring in. It seems that all the major libraries depend on the lowest version of the target framework.
For example, if the target is net 8.0, the package will be 8.0.0. If the target is net 9.0, the …
=> build: Change dependency assets

.github/workflows/release.yml
Restricts usage of the `NUGET_TOKEN` to only the `publish` environment.
=> chore: restrict publish to environment

src/OpenFeature/Providers/Memory/InMemoryProvider.cs, test/OpenFeature.Tests/Providers/Memory/InMemoryProviderTests.cs
- Update InMemoryProvider to return an ErrorType with a default value instead of throwing exceptions
- Add unit test to cover the new behavior
Fixes #441
=> refactor: InMemoryProvider throwing when types mismatched

README.md, src/OpenFeature/Api.cs
- Clarifies the behaviour of SetProviderAsync. Exceptions can be thrown by a provider during initialization.
Fixes #445
=> docs: update documentation on SetProviderAsync

renovate.json
Signed-off-by: André Silva <2493377+askpt@users.noreply.github.com>
This pull request updates the Renovate configuration to enhance dependency management workflows. The most notable changes include enabling dependency dashboard approval and specifying that dependencies should not be recreated automatically.
Changes to Renovate configuration:
* [`renovate.json`](diffhunk://#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57L5-R7): Enabled the `dependencyDashboardApproval` setting to require manual approval for dependency updates.
* [`renovate.json`](diffhunk://#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57L5-R7): Added the `recreateWhen` setting with a value of `"never"` to prevent automatic recreation of dependency updates.
Fixes #448
I followed …
=> ci: update renovate configuration to fix immortal PRs

README.md, src/OpenFeature.DependencyInjection/Internal/FeatureLifecycleManager.cs, src/OpenFeature.DependencyInjection/OpenFeatureBuilderExtensions.cs, src/OpenFeature.DependencyInjection/OpenFeatureOptions.cs, test/OpenFeature.DependencyInjection.Tests/FeatureLifecycleManagerTests.cs, test/OpenFeature.DependencyInjection.Tests/NoOpHook.cs, test/OpenFeature.DependencyInjection.Tests/OpenFeatureBuilderExtensionsTests.cs, test/OpenFeature.IntegrationTests/FeatureFlagIntegrationTest.cs, test/OpenFeature.IntegrationTests/OpenFeature.IntegrationTests.csproj
- This adds a new OpenFeatureBuilder extension method to add global or not domain-bound hooks to the OpenFeature Api.
Fixes #456
We inject any provided Hooks as Singletons in the DI container. We use keyed singletons and use the class name as the key. Maybe we'd want to use a different name to avoid conflicts?
I've done some manual testing with a sample weatherforecast ASP.NET Core web application
=> feat: Add Extension Method for adding global Hook via DependencyInjection

README.md, src/OpenFeature.DependencyInjection/Internal/EventHandlerDelegateWrapper.cs, src/OpenFeature.DependencyInjection/Internal/FeatureLifecycleManager.cs, src/OpenFeature.DependencyInjection/OpenFeatureBuilderExtensions.cs, src/OpenFeature.DependencyInjection/OpenFeatureOptions.cs, test/OpenFeature.DependencyInjection.Tests/FeatureLifecycleManagerTests.cs, test/OpenFeature.DependencyInjection.Tests/OpenFeatureBuilderExtensionsTests.cs, test/OpenFeature.IntegrationTests/FeatureFlagIntegrationTest.cs
- Introduces a new extension method in the OpenFeature.DependencyInjection package which allows consumers to add, at a global/api level, a handler. 
Example usage:
```csharp
builder.Services.AddOpenFeature(feature =>
{
feature.AddHostedFeatureLifecycle()
.AddInMemoryProvider()
.AddHandler(ProviderEventTypes.ProviderReady, (@event) => { Console.WriteLine("{0}", @event!.ProviderName); })
.AddHandler(ProviderEventTypes.ProviderReady, sp => (@event) =>
{
var logger = sp.GetRequiredService<ILogger<Program>>();
logger.LogInformation("Provider Ready");
});
});
```
Fixes #457
=> feat: add AddHandler extension method to Dependency Injection package

OpenFeature.slnx, README.md, build/Common.samples.props, samples/AspNetCore/Program.cs, samples/AspNetCore/Properties/launchSettings.json, samples/AspNetCore/README.md, samples/AspNetCore/Samples.AspNetCore.csproj, samples/AspNetCore/appsettings.Development.json, samples/AspNetCore/appsettings.json, samples/Directory.Build.props
- Adds simple a AspNetCore web application with a `/welcome` minimal API that will show one of two messages based the configuration of the `InMemory` feature provider.
While the [README](https://github.com/open-feature/dotnet-sdk/blob/6c44db9237748735a22a162a88f61b2de7f3e9bd/README.md) for OpenFeature dotnet is pretty comprehensive, I think it can be quite intimidating to developers who are unfamilar with feature flagging and OpenFeature. Providing a basic application that can be cloned locally and run with minimal setup would improve the onboarding and upskill experience.
Additionally, as a contributor I find myself frequently creating simple applications to test out changes to OpenFeature. This would save the effort of stashing local changes and make it easier to more quickly test or …
=> docs: Add AspNetCore sample app

.github/workflows/release.yml
This pull request includes a small change to the `.github/workflows/release.yml` file. The change removes the `release-type: simple` configuration from the `jobs:` section, potentially altering the release behavior.
I would imagine, since we are putting this setting here, it won't read from the configuration file.
=> ci: Fix config for release

src/OpenFeature/Telemetry/EvaluationEventBuilder.cs, test/OpenFeature.Tests/Telemetry/EvaluationEventBuilderTests.cs
Signed-off-by: André Silva <2493377+askpt@users.noreply.github.com>
This pull request introduces a generic type parameter `T` to the `EvaluationEventBuilder` class to enhance its flexibility and adaptability for different data types. Corresponding updates have been made to the test suite to accommodate this change.
* The `EvaluationEventBuilder` class now includes a generic type parameter `T`, allowing it to handle different data types for evaluation events. This change affects its definition, the `Default` property, and the `Build` method. (`src/OpenFeature/Telemetry/EvaluationEventBuilder.cs`, [src/OpenFeature/Telemetry/EvaluationEventBuilder.csL9-R24](diffhunk://#diff-6bccdfe3ff3572320900eca32b1f88adaffd0ca3dfb9c01a152a7aa16d271746L9-R24))
* Updated the `EvaluationEventBuilderTests` …
=> fix: Add generic to evaluation event builder

src/OpenFeature/EventExecutor.cs, test/OpenFeature.Tests/OpenFeatureClientTests.cs
- Adds a default placeholder name that gets generated when a Client is generated. This is inspired from the Java SDK (see [EventSource.java](https://github.com/open-feature/java-sdk/blob/0515ad54c4f71863373eb1b7f429393923b27d90/src/main/java/dev/openfeature/sdk/EventSupport.java#L40)). The exception is thrown when an optional client name is specified when retrieving a client from `Api.Instance`. When no name is specified we use a generated one.
Fixes #491
=> fix: ArgumentNullException when creating a client with optional name

README.md, src/OpenFeature.DependencyInjection/OpenFeatureBuilderExtensions.cs, test/OpenFeature.DependencyInjection.Tests/OpenFeatureBuilderExtensionsTests.cs
In #512 I needed to tweak the sample AspNetCore application to pass Hook options to the MetricsHook. I noticed that in order to pass the options I needed to use the delegate based approach, while discarding the `serviceProvider`, like:
```csharp
featureBuilder.AddHostedFeatureLifecycle()
.AddHook(_ => new MetricsHook(metricsHookOptions))
```
It would be simpler and easier for devs to interact with a third overload that allows them to pass an instance of the hook that they want to interact with, like so:
```csharp
featureBuilder.AddHostedFeatureLifecycle()
.AddHook(new MetricsHook())
```
=> feat: Add Hook Dependency Injection extension method with Hook instance

README.md, src/OpenFeature/Hooks/TraceEnricherHook.cs, src/OpenFeature/Hooks/TraceEnricherHookOptions.cs, test/OpenFeature.Tests/Hooks/TraceEnricherHookOptionsTests.cs, test/OpenFeature.Tests/Hooks/TraceEnricherHookTests.cs
Adds `TraceEnricherHookOptions`, largely a copy of `MetricHookOptions` from #512, to enrich the `feature_flag.evaluation` span event.
Example usage:
```csharp
var traceHookOptions = TraceEnricherHookOptions.CreateBuilder()
.WithCustomDimension("key1", "value1")
.WithFlagEvaluationMetadata("provider", s => s.GetString("provider"))
.Build();
featureBuilder.AddHostedFeatureLifecycle()
.AddHook(new TraceEnricherHook(traceHookOptions));
```
These adds tags to the event associated with the span. Below is an example with the above custom dimension and metadata callback:
Fixes #516
I kept the builder method names `WithCustomDimension` and `WithFlagEvaluationMetadata`, maybe this should be different for Traces? In the Java implementation the both hook options look very similar: …
=> feat: Add TraceEnricherHookOptions Custom Attributes

release-please-config.json, src/OpenFeature.DependencyInjection/OpenFeature.DependencyInjection.csproj, src/OpenFeature.DependencyInjection/README.md
This adds a README to the Dependency Injection NuGet package with a deprecation notice or warning.
Fixes #472
=> chore: Add README and Deprecation notice to DependencyInjection library
