open-feature/dotnet-sdk

.github/workflows/code-coverage.yml, README.md, build/Common.tests.props, test/OpenFeature.Tests/OpenFeature.Tests.csproj
=> Add code coverage build

README.md
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> Update contributors thank you message

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/documentation.yaml, .github/ISSUE_TEMPLATE/feature.yaml
Copy issue templates from node-sdk
=> Chore: Add basic issue templates

test/OpenFeature.Tests/OpenFeatureHookTests.cs
When error is thrown during calling a before hook the default
value should be returned
https://github.com/open-feature/spec/pull/110
=> Chore: Add test to cover spec 4.4.7

README.md
Add openssf badge for https://bestpractices.coreinfrastructure.org/en/projects/6250
=> chore: Add openssf badge

.gitignore, .vscode/launch.json, .vscode/tasks.json, src/OpenFeature.SDK/OpenFeature.cs, src/OpenFeature.SDK/OpenFeatureClient.cs, test/OpenFeature.SDK.Tests/OpenFeatureHookTests.cs
- Adds client context
- Updates context merge behavior
- Adds vs code settings / assocaited gitignores
=> feat: update ctx merge order, add client ctx

.config/dotnet-tools.json, .github/workflows/release-package.yml, .gitignore, CONTRIBUTING.md, OpenFeature.SDK.sln, build/Common.prod.props, build/RELEASING.md, build/dotnet-releaser.toml, test/OpenFeature.SDK.Tests/OpenFeature.SDK.Tests.csproj
#44
- Update doco to reflect changes
- Configure dotnet-releaser and add to tools
- Update release action to use dotnet-release
- Add description to package, and packaged
Once approved will create the following labels and clean up overlapping to avoid confusion
- 🚨 Breaking Changes = `breaking-change`
- ✨ New Features = `feature`
- 🐛 Bug Fixes = `bug`
- 🚀 Enhancements = `enhancement`
- 🧰 Maintenance = `maintenance`
- 🏭 Tests = `tests`, `test`
- 🛠 Examples = `examples`
- 📚 Documentation = `documentation`
- 🌎 Accessibility = `translations`
- 📦 Dependencies = `dependencies`
- 🧰 Misc = `misc`
=> feat: Use dotnet-releaser to automate releases

release-please-config.json
=> fix!: use correct path to extra file

.github/workflows/release.yml
=> fix: change NUGET_API_KEY -> NUGET_TOKEN

.github/workflows/release.yml
Signed-off-by: Todd Baert <toddbaert@gmail.com>
=> fix: add dir to publish

README.md
#71
- remove wip badge from readme
- remove providers tba, this will be replaced with a link to docs.openfeature.dev and contribs in the future.
=> chore: add spec badge

README.md
Signed-off-by: Ryan Lamb <4955475+kinyoklion@users.noreply.github.com>
Updates the README with a working basic usage.
The NoOpProvider was used in the usage example, but now it is internal, so we either need to not use it, as done here, or we should consider making it non-internal.
=> chore: Update README basic usage.

.github/workflows/code-coverage.yml, .github/workflows/dotnet-format.yml, .github/workflows/linux-ci.yml, .github/workflows/windows-ci.yml, global.json, test/OpenFeature.Tests/OpenFeature.Tests.csproj
Since .net 7 was released this week, we should also run our test suite across it
=> feat: include net7 in the test suit

src/OpenFeature/Constant/Reason.cs
As per: https://github.com/open-feature/spec/blob/7ed7442c40d4e766424671258846b21a96adda70/specification/types.md#resolution-details
Signed-off-by: Todd Baert <toddbaert@gmail.com>
=> feat: add STATIC, CACHED reasons

README.md
- adapts readme according to general template
- adds missing sections
Fixes #119
=> docs: adapt README according to general template

src/OpenFeature/OpenFeature.csproj
- This PR is to close the issue related to the missing README.md file from the Nuget website.
Fixes #138 
I followed the instructions from the website but I am not sure how to test if it's working correctly.
=> docs: Add README.md to the nuget package

README.md
- adds release please version range
This should work fine as long as the spec version is never the same as the release. Unfortunately, I had to include both tags because otherwise it introduces formatting issues.
=> docs: add release please version range

Directory.Packages.props, build/Common.props, build/Common.tests.props, src/OpenFeature/OpenFeature.csproj, test/OpenFeature.Benchmarks/OpenFeature.Benchmarks.csproj, test/OpenFeature.E2ETests/OpenFeature.E2ETests.csproj, test/OpenFeature.Tests/OpenFeature.Tests.csproj
See: open-feature/dotnet-sdk-contrib#136
=> chore: Enable Central Package Management (CPM)

.editorconfig
Typo that was made under PR https://github.com/open-feature/dotnet-sdk/pull/242
=> fix: invalid editorconfig

.gitignore, .specrc
Signed-off-by: Justin Abrahms <justin@abrah.ms>
=> chore: Support for determining spec support for the repo

renovate.json
- update renovate config to extend the shared config
This will use the shared confirm managed in the community tooling repo. The noteworthy changes are are merging for minor versions that are sub-v1.
https://github.com/open-feature/community-tooling/blob/main/renovate.json
=> chore: update renovate config to extend the shared config

test/OpenFeature.IntegrationTests/FeatureFlagIntegrationTest.cs, test/OpenFeature.IntegrationTests/OpenFeature.IntegrationTests.csproj
This pull request to `test/OpenFeature.IntegrationTests` includes changes to enhance the feature flag integration tests and update the project dependencies. The most important changes include modifying the `CreateServerAsync` method to accept a `ServiceLifetime` parameter and updating the `xunit.runner.visualstudio` package reference to include additional assets.
Enhancements to feature flag integration tests:
* [`test/OpenFeature.IntegrationTests/FeatureFlagIntegrationTest.cs`](diffhunk://#diff-3e5726e0b3cb41e2598e2a5deca805de5566b16854bf0bcba649509228c73726L30-R30): Updated the `VerifyFeatureFlagBehaviorAcrossServiceLifetimesAsync` method to pass the `serviceLifetime` parameter to the `CreateServerAsync` method.
* [`test/OpenFeature.IntegrationTests/FeatureFlagIntegrationTest.cs`](diffhu …
=> ci: Add integration tests to the test action

.github/workflows/codeql-analysis.yml
This pull request includes a small change to the `.github/workflows/codeql-analysis.yml` file. The change adds 'actions' to the list of languages supported by CodeQL analysis.
* [`.github/workflows/codeql-analysis.yml`](diffhunk://#diff-63bd641104d10e25f141d518a16b22a151d125e12701df2f9e79734b23b90188L35-R35): Added 'actions' to the `language` matrix for CodeQL analysis.
=> ci: Add GH Actions as a scanned artifact for CodeQL

build/Common.props
- NuGet offers built in functionality for analyzing packages that are included in a software project. These changes will ensure msbuild outputs warnings when dependencies are flagged up with vulnerabilities.
Fixes #444
=> chore: add NuGet auditing

README.md
This pull request includes a small change to the `README.md` file. The change updates the specification badge to reflect the new version 0.8.0.
Fixes #204
=> docs: Update README with spec version

samples/AspNetCore/Program.cs
- fixes the sample build warning
the `builder` name override the `WebApplicationBuilder`
=> chore: fix sample build warning
